#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE safepilgrim;
    CREATE DATABASE digital_ids;
    CREATE DATABASE geofencing;
    CREATE DATABASE analytics;
    CREATE DATABASE emergency;
    
    GRANT ALL PRIVILEGES ON DATABASE safepilgrim TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE digital_ids TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE geofencing TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE analytics TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE emergency TO $POSTGRES_USER;
EOSQL
