server:
  port: 8080

spring:
  application:
    name: digital-id-service
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/safepilgrim_digitalid}
    username: ${DATABASE_USERNAME:safepilgrim}
    password: ${DATABASE_PASSWORD:safepilgrim123}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.safepilgrim.digitalid: INFO
    org.springframework.web: INFO
